apiVersion: apps/v1
kind: Deployment
metadata: 
  name: fortune-cookie
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: fortune-cookie
  template:
    metadata:
      labels:
        app: fortune-cookie
  spec:
    containers:
      - name: backend
        image: acosmussi/backend_image:latest
      - name: frontend
        image: acosmussi/frontend_image:latest
        ports:  
          - containerport: 8080
