services:
  backend:
    image: backend_image
    build: ./backend/
    environment:
      REDIS_DNS: "localhost"
    ports:
      - "90:9000"
  
  frontend:
    image: frontend_image
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    environment:
      BACKEND_PORT: "9000"
      BACKEND_DNS: "localhost"
    depends_on: 
      - backend
    ports:
      - "80:8080"