services:
  backend:
    image: backend_image
    build: ./backend/
    ports:
      - "90:9000"
  
  frontend:
    image: frontend_image
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on: 
      - backend
    ports:
      - "80:8080"